### ISSUE TITLE
Please update the README to include the October 2019 Philly list of Contributors

### ISSUE THREAD

**Issue by jacebryan** [SFDO-Sprint-2019-Philadelphia/transfer-equivalency#31]
Hello transfer-equivalency team! 

I am noticing that only those contributors from Detroit (project origination sprint) have been captured in the list for Philly. Can the project Scribe please update the list to include the Philly contributors? Or add a comment to this Issue and I will update the list?

Thank you! :)

**Comment by robertbwatson** [comment]
@jacebryan I think @MatthewBlanski already did this :)

**Comment by robertbwatson** [comment]
Maybe @MatthewBlanski could update the "Project Team Accomplishments" to highlight what was worked on at the Philly sprint?

**Comment by jacebryan** [comment]
Apologies @MatthewBlanski! @robertbwatson is right - you already did update the list of Contributors for Philly. :) 

I 2nd an update to the "Project Team Accomplishments" :)

**Comment by jacebryan** [comment]
I'm going to close this issue and reopen another issue for the ask to update the Project Team Accomplishments for Philly.
